@startuml
!theme plain
top to bottom direction

class node5 as "AllColorVariables.tsx"
class node48 as "App.tsx"
class node54 as "index.tsx"

package components {
  class FixedCamera as "FixedCamera.tsx"
  class ObjectLoad as "ObjectLoad.tsx"

  package overworld{
    class node43 as "Overworld.tsx"
    class node73 as "Player.tsx"

    package objects {
       class node59 as "Text.tsx"
       class node72 as "CreateText.tsx"
       class node15 as "Tube.tsx"
       class node40 as "Button.tsx"
    }

    package Plattforms {
      class node57 as "DesignPlatform.tsx"
      class node1 as "EngineeringPlatform.tsx"
      class node24 as "Floor.tsx"
      class node18 as "MainPlatform.tsx"
      class node78 as "MonitoringPlatform.tsx"
      class node10 as "PartsPlatform.tsx"
      class node47 as "ProductionPlatform.tsx"
      class node27 as "ShipmentPlatform.tsx"
      class node56 as "SimplePlatform.tsx"
      class node71 as "SimpleText.tsx"
      class node29 as "Stair.tsx"
    }
  }

  package minigames {
    package shipment {
      class node42 as "FinalTube.tsx"
      class node75 as "Grid.tsx"
      class node32 as "ShipmentGame.tsx"
      class node22 as "Sphere.tsx"
      class node64 as "Tile.tsx"
      class node28 as "Tube.tsx"
      class node52 as "WinScreen.tsx"
      class node14 as "victoryScreen.css"
    }
  }

  package startscreen {
    class node37 as "LoadingScreen.tsx"
    class node58 as "Video.tsx"
  }

  package UI {
   class node39 as "NavigationButton.tsx"
   class node45 as "buttonstyle.css"
   class node30 as "components/InfoButton.tsx"
  }
}

node43  <-[#595959,plain]up-  FixedCamera
node32  <-[#595959,plain]down-  FixedCamera

node43  <-[#595959,plain]up---  node73
node43  <-[#595959,plain]--  Plattforms
overworld  <-[#595959,plain]-  ObjectLoad
Plattforms  <-[#595959,plain]up-  objects
node1   <-[#595959,plain]-  node56
node24  <-[#595959,plain]-  node56
node18  <-[#595959,plain]-  node56
node78  <-[#595959,plain]-  node56
node10  <-[#595959,plain]-  node56
node47  <-[#595959,plain]-  node56
node27  <-[#595959,plain]-  node56
node57  <-[#595959,plain]-  node56
node56  <-[#595959,plain]-  node71
node42  <-[#595959,plain]-  node32
node42  <-[#595959,plain]-  node22
node42  <-[#595959,plain]-  node64
node75  <-[#595959,plain]-  node42
node75  <-[#595959,plain]-  node64
node32  <-[#595959,plain]-  UI
node43  <-[#595959,plain]-  UI
shipment  <-[#595959,plain]-  ObjectLoad
node32  <-[#595959,plain]-  node75
node32  <-[#595959,plain]-  node52
node32  <-[#595959,plain]-  node14
node22  <-[#595959,plain]-  node32
node64  <-[#595959,plain]-  node28
node48  <-[#595959,plain]-  node43
node48  <-[#595959,plain]- node37
node54  <-[#595959,plain]-  node48
node37  <-[#595959,plain]-  node58
@enduml